import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

// Nunito Sans with all weights
const nunitoSans = Nunito_Sans({
  subsets: ["latin", "latin-ext"],
  display: 'swap',
  variable: '--font-nunito',
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunitoSans.variable}`}>
     <body className="font-sans antialiased" suppressHydrationWarning>
  <Header />
  {children}
  <Footer />
</body>
    </html>
  );
}